# Generated by Django 4.2.25 on 2025-10-18 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Province name (e.g., Camarines Norte)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version (e.g., camarines-norte)', unique=True)),
                ('active', models.BooleanField(default=True, help_text='Show in province listings')),
                ('featured', models.BooleanField(default=False, help_text='Highlight on homepage')),
                ('description', models.TextField(blank=True, help_text='Province description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Municipality name (e.g., Daet)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly version (e.g., daet)')),
                ('active', models.BooleanField(default=True, help_text='Show in municipality listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(help_text='Parent province', on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='api.province')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
                'unique_together': {('province', 'slug')},
            },
        ),
    ]
