# Generated by Django 5.2.7 on 2025-10-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_province_municipality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name'], 'verbose_name': 'City/Municipality', 'verbose_name_plural': 'Cities/Municipalities'},
        ),
        migrations.AddField(
            model_name='listing',
            name='barangay',
            field=models.CharField(blank=True, help_text='Barangay (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(help_text='City/Municipality/Barangay', max_length=200),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='active',
            field=models.BooleanField(default=True, help_text='Show in city/municipality listings'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(help_text='City/Municipality name (e.g., Daet, Cebu City)', max_length=100),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version (e.g., daet, cebu-city)'),
        ),
    ]
