# Generated by Django 5.2.7 on 2025-10-18 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_municipality_options_listing_barangay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('government', 'Government'), ('community', 'Community'), ('alert', 'Alert'), ('infrastructure', 'Infrastructure'), ('safety', 'Safety'), ('health', 'Health'), ('business', 'Business')], default='general', max_length=50)),
                ('barangay', models.CharField(blank=True, help_text='Barangay (optional)', max_length=100)),
                ('contact_info', models.CharField(blank=True, help_text='Contact information for inquiries', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, help_text='When announcement is no longer relevant', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.province')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['province', 'municipality', '-created_at'], name='api_announc_provinc_89d037_idx'), models.Index(fields=['priority', '-created_at'], name='api_announc_priorit_84c394_idx'), models.Index(fields=['announcement_type'], name='api_announc_announc_d9de84_idx')],
            },
        ),
    ]
