# Generated by Django 5.2.7 on 2025-11-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_province_wide',
            field=models.BooleanField(default=False, help_text='Show this announcement in all municipalities within the province'),
        ),
    ]
