# Generated by Django 5.2.7 on 2025-11-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_announcement_is_province_wide'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pay_period',
            field=models.CharField(blank=True, choices=[('per_day', 'Per Day'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('not_applicable', 'Not Applicable')], default='not_applicable', help_text='Pay period for job listings', max_length=20, null=True),
        ),
    ]
