# Generated by Django 5.2.7 on 2025-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_listing_pay_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='vehicle_condition',
            field=models.CharField(blank=True, choices=[('brand_new', 'Brand New'), ('like_new', 'Like New'), ('used_excellent', 'Used - Excellent'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair'), ('for_parts', 'For Parts')], help_text='Vehicle condition (used when category is Vehicle)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('not_applicable', 'Not Applicable')], help_text='Fuel type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle make/brand (e.g., Toyota, Honda)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_mileage',
            field=models.IntegerField(blank=True, help_text='Odometer reading in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., Vios, City)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('not_applicable', 'Not Applicable')], help_text='Transmission type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('van', 'Van'), ('suv', 'SUV'), ('bus', 'Bus'), ('boat', 'Boat'), ('other', 'Other')], help_text='Type of vehicle', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_year',
            field=models.IntegerField(blank=True, help_text='Manufacturing year', null=True),
        ),
    ]
