# Generated by Django 5.2.7 on 2025-11-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_listing_vehicle_condition_listing_vehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Barangay name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly version')),
                ('active', models.BooleanField(default=True, help_text='Show in barangay listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(help_text='Parent city/municipality', on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='api.municipality')),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangays',
                'ordering': ['name'],
                'unique_together': {('municipality', 'slug')},
            },
        ),
    ]
