# Generated by Django 5.2.7 on 2025-11-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_barangay'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barangay',
            unique_together={('municipality', 'name')},
        ),
        migrations.AlterField(
            model_name='barangay',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version', max_length=150),
        ),
    ]
