# Generated by Django 5.2.7 on 2025-11-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_barangay_unique_together_alter_barangay_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barangay',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='barangay',
            name='psgc_code',
            field=models.CharField(blank=True, help_text='10-digit PSGC code', max_length=20, null=True, unique=True),
        ),
    ]
