# Generated by Django 5.2.7 on 2025-11-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_barangay_unique_together_barangay_psgc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='type',
            field=models.CharField(choices=[('City', 'City'), ('Mun', 'Municipality')], default='Mun', help_text='Designation: City or Municipality', max_length=4),
        ),
    ]
