# Generated by Django 5.2.7 on 2025-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_municipality_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_municipality_wide',
            field=models.BooleanField(default=False, help_text='Show this announcement in all barangays within the municipality'),
        ),
    ]
