# Generated by Django 5.2.7 on 2025-11-20 20:54

import django.db.models.deletion
from django.db import migrations, models


def clear_barangay_data(apps, schema_editor):
    """Clear all barangay data from listings and announcements before conversion"""
    Listing = apps.get_model('api', 'Listing')
    Announcement = apps.get_model('api', 'Announcement')

    # Set all barangay fields to empty string (will become NULL after conversion)
    Listing.objects.all().update(barangay='')
    Announcement.objects.all().update(barangay='')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_is_municipality_wide_to_announcement'),
    ]

    operations = [
        # Step 1: Clear all existing barangay data
        migrations.RunPython(clear_barangay_data, migrations.RunPython.noop),

        # Step 2: Remove the old CharField barangay fields
        migrations.RemoveField(
            model_name='announcement',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='barangay',
        ),

        # Step 3: Add new ForeignKey barangay fields
        migrations.AddField(
            model_name='announcement',
            name='barangay',
            field=models.ForeignKey(
                blank=True,
                help_text='Barangay (optional)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='announcements',
                to='api.barangay'
            ),
        ),
        migrations.AddField(
            model_name='listing',
            name='barangay',
            field=models.ForeignKey(
                blank=True,
                help_text='Barangay (optional)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='listings',
                to='api.barangay'
            ),
        ),
    ]
