# Generated by Django 5.2.7 on 2025-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_change_barangay_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='type',
            field=models.CharField(choices=[('City', 'City'), ('Mun', 'Municipality'), ('SubMun', 'Sub-Municipality')], default='Mun', help_text='Designation: City, Municipality, or Sub-Municipality (Manila districts)', max_length=6),
        ),
    ]
