# Generated by Django 5.2.7 on 2025-11-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_submun_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='psgc_code',
            field=models.CharField(blank=True, help_text='10-digit PSGC code', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='province',
            name='psgc_code',
            field=models.CharField(blank=True, help_text='10-digit PSGC code', max_length=20, null=True, unique=True),
        ),
    ]
