# Generated by Django 5.2.7 on 2025-11-24 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_municipality_psgc_code_province_psgc_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='api_listing_island_393c74_idx',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='island',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='City/Municipality', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.municipality'),
        ),
        migrations.AddField(
            model_name='listing',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Province', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.province'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['province', 'status'], name='api_listing_provinc_f00502_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['municipality', 'status'], name='api_listing_municip_652edc_idx'),
        ),
    ]
