# Generated by Django 5.2.7 on 2025-12-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_listing_api_listing_island_393c74_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_large',
            field=models.ImageField(blank=True, help_text='Large (1200x800) - detail page', upload_to='listings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_medium',
            field=models.ImageField(blank=True, help_text='Medium (500x333) - desktop cards', upload_to='listings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_small',
            field=models.ImageField(blank=True, help_text='Small (300x200) - mobile cards', upload_to='listings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_thumb',
            field=models.ImageField(blank=True, help_text='Thumbnail (150x100)', upload_to='listings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_xlarge',
            field=models.ImageField(blank=True, help_text='Extra large (1920x1280) - desktop lightbox', upload_to='listings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_medium',
            field=models.ImageField(blank=True, help_text='Medium (400x400) - profile page', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_small',
            field=models.ImageField(blank=True, help_text='Small (200x200) - standard avatar', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_thumb',
            field=models.ImageField(blank=True, help_text='Thumbnail (100x100)', upload_to='profiles/'),
        ),
    ]
