# Generated by Django 5.2.7 on 2025-12-04 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_listingimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this moderator is currently active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment')),
                ('assigned_by', models.ForeignKey(help_text='Super admin who assigned this moderator', limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_assignments', to=settings.AUTH_USER_MODEL)),
                ('province', models.OneToOneField(help_text='Province this user moderates', on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='api.province')),
                ('user', models.OneToOneField(help_text='User assigned as province moderator', on_delete=django.db.models.deletion.CASCADE, related_name='province_moderator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Province Moderator',
                'verbose_name_plural': 'Province Moderators',
                'ordering': ['province__name'],
            },
        ),
    ]
