# Generated by Django 5.2.7 on 2025-12-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_province_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='City/Municipality (optional for province-wide announcements)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='api.municipality'),
        ),
    ]
