# Generated by Django 5.2.7 on 2025-12-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_make_announcement_municipality_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero background image for province page (recommended: 1920x600 or wider)', null=True, upload_to='provinces/heroes/'),
        ),
    ]
