# Generated by Django 5.2.7 on 2025-12-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_province_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero background image for municipality page (recommended: 1920x600 or wider)', null=True, upload_to='municipalities/heroes/'),
        ),
    ]
