# Generated by Django 5.2.7 on 2025-12-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_municipality_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Show in 'Popular Destinations' section on homepage"),
        ),
    ]
